# Error Team - Backend Service
apiVersion: v1
kind: Service
metadata:
  name: backend-service
  namespace: errorteam
  labels:
    app: backend
    team: error-team
spec:
  type: ClusterIP
  ports:
  - port: 8080
    targetPort: 8080
    protocol: TCP
    name: http
  selector:
    app: backend
